name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: fkohrt/action-languagetool@v1.2.0
        with:
          # github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-check
          # Change reporter level if you need.
          level: error
          filter_mode: nofilter
          disabled_categories: 'A_INFINITIVE,TYPOS'
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 16
      - run: yarn install
      - run: yarn run build

